let phoneDetails = JSON.parse(localStorage.getItem('phoneDetails'));
let divforPhoneDetails = document.createElement('div');
divforPhoneDetails.id = "divforPhoneDetails";
document.body.appendChild(divforPhoneDetails);
let divforphoneImage = document.createElement('div');
let phoneimage = document.createElement("img");
phoneimage.src = phoneDetails.PhoneImageUrl;
phoneimage.style.height = "350px";
phoneimage.style.width = "250px";
divforphoneImage.appendChild(phoneimage);
divforPhoneDetails.appendChild(divforphoneImage);
let divforphoneSpecs = document.createElement('div');
divforphoneSpecs.style.display = "flex";
divforphoneSpecs.style.flexDirection = "column";
let phonename = document.createElement("p");
phonename.innerHTML = "Phone Name&nbsp;:&nbsp;" + "<b>" + phoneDetails.phoneName + "</b>";
phonename.className = "phoneSpecs";
divforphoneSpecs.appendChild(phonename);
let phoneram = document.createElement("p");
phoneram.innerHTML = "Ram &nbsp;: " + "<b>" + phoneDetails.Ram + "</b>";
phoneram.className = "phoneSpecs";
divforphoneSpecs.appendChild(phoneram);
let phoneprocessor = document.createElement('p');
phoneprocessor.innerHTML = "Processor&nbsp;:&nbsp;" + "<b>" + phoneDetails.Processor + "</b>";
phoneprocessor.className = "phoneSpecs";
divforphoneSpecs.appendChild(phoneprocessor);
let phonePrice = document.createElement('p');
phonePrice.innerHTML = "Price&nbsp;:&nbsp;" + "<b>" + phoneDetails.Price + "</b>";
phonePrice.className = "phoneSpecs";
divforphoneSpecs.appendChild(phonePrice);
let phoneBattery = document.createElement('p');
phoneBattery.className = "phoneSpecs";
phoneBattery.innerHTML = "Battery&nbsp;:&nbsp;" + "<b>" + phoneDetails.Battery + "</b>";
divforphoneSpecs.appendChild(phoneBattery);
let phoneDisplay = document.createElement('p');
phoneDisplay.className = "phoneSpecs";
phoneDisplay.innerHTML = "Display&nbsp;:&nbsp;" + "<b>" + phoneDetails.Display + "</b>";
divforphoneSpecs.appendChild(phoneDisplay);
let phoneOS = document.createElement('p');
phoneOS.className = "phoneSpecs";
phoneOS.innerHTML = "OS&nbsp;:&nbsp;" + "<b>" + phoneDetails.OS + "</b>";
divforphoneSpecs.appendChild(phoneOS);
let phoneStorage = document.createElement('p');
phoneStorage.className = "phoneSpecs";
phoneStorage.innerHTML = "Storage&nbsp;:&nbsp;" + "<b>" + phoneDetails.Storage + "</b>";
divforphoneSpecs.appendChild(phoneStorage);
let phoneFrontCam = document.createElement('p');
phoneFrontCam.className = "phoneSpecs";
phoneFrontCam.innerHTML = "FrontCamera&nbsp;:&nbsp;" + "<b>" + phoneDetails.frontCamera + "</b>";
divforphoneSpecs.appendChild(phoneFrontCam);
let phonerearCam = document.createElement('p');
phonerearCam.className = "phoneSpecs";
phonerearCam.innerHTML = "RearCamera&nbsp;:&nbsp;" + "<b>" + phoneDetails.rearCam + "</b>";
divforphoneSpecs.appendChild(phonerearCam);
divforPhoneDetails.appendChild(divforphoneSpecs);
